public class PlanException  extends Exception{
    private int id;
    private int newID;

    public PlanException(int id) {
        this.id = id;
        this.newID = generatID();
    }

    public String toString() {
        return " The Plan ID was not valid and a new ID ( " + id
                + " ) is generated by admin and assigned for the Plan ";
    }

    public int getId() {
        return newID;
    }

    public int generatID() {
        int id = (int) ((Math.random() * ((3999999 - 3000000) + 1)) + 3000000);
        return id;
    }
}
