/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author parham
 */
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class UpdateUI extends javax.swing.JFrame {

    MobilePlan plan;
    UserUi userUI;

    /**
     * Creates new form updateUI
     */
    public UpdateUI(MobilePlan plan, UserUi userUI) {
        initComponents();
        this.plan = plan;
        this.userUI = userUI;
        PersonalPlan.setEnabled(false);
        BusinessPlan.setEnabled(false);
        usernameField.setText(plan.getUserName());
        modelField.setText(plan.getHandSetModel());
        memorySizeField.setText(plan.handSet.getMemorySize() + "");
        priceField.setText(plan.getHandSetPrice() + "");
        internetQuotaField.setText(plan.internetQuota + "");
        typeBox.setSelectedItem(plan.handSet.getMobileType().toString());
        capLimitField.setText(plan.capLimit + "");
        dayField.setText(plan.getExpiryDate().getDay() + "");
        monthField.setText(plan.getExpiryDate().getMonth() + "");
        yearField.setText(plan.getExpiryDate().getYear() + "");
        if (plan instanceof PersonalPlan) {
            PersonalPlan.setSelected(true);
            BusinessPlan.setSelected(false);
            employeesField.setVisible(false);
            numberE.setVisible(false);
            cityOrABN.setText("City");
            cityOrABNField.setText(((PersonalPlan) plan).getCity());
        } else {
            PersonalPlan.setSelected(false);
            BusinessPlan.setSelected(true);
            cityOrABN.setText("ABN");
            cityOrABNField.setText(((BusinessPlan) plan).getNumE() + "");
            numberE.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        numberE = new javax.swing.JLabel();
        dayField = new javax.swing.JTextField();
        monthField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        cityOrABNField = new javax.swing.JTextField();
        employeesField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cityOrABN = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        typeBox = new javax.swing.JComboBox<>();
        planIDfield = new javax.swing.JTextField();
        usernameField = new javax.swing.JTextField();
        modelField = new javax.swing.JTextField();
        memorySizeField = new javax.swing.JTextField();
        internetQuotaField = new javax.swing.JTextField();
        capLimitField = new javax.swing.JTextField();
        updateButton = new javax.swing.JButton();
        clearButtun = new javax.swing.JButton();
        PersonalPlan = new javax.swing.JRadioButton();
        BusinessPlan = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Model");

        jLabel4.setText("OS Type");

        jLabel5.setText("Memory Size");

        jLabel6.setText("Price");

        jLabel7.setText("Internet Quota");

        jLabel8.setText("Cap Limit");

        jLabel9.setText("Expiry Date");

        jLabel20.setText("Day");

        jLabel21.setText("Year");

        numberE.setText("NO. Employee");

        cityOrABNField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityOrABNFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        jLabel2.setText("Mobile Phone");

        cityOrABN.setText("City");

        jLabel24.setText("Month");

        jLabel25.setText("Plan ID");

        typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ios", "Android", "windows" }));

        planIDfield.setEnabled(false);
        planIDfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planIDfieldActionPerformed(evt);
            }
        });

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        updateButton.setText("update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        clearButtun.setText("Clear");
        clearButtun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtunActionPerformed(evt);
            }
        });

        PersonalPlan.setText("Personal Plan");
        PersonalPlan.setEnabled(false);
        PersonalPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalPlanActionPerformed(evt);
            }
        });

        BusinessPlan.setText("Business Plan");
        BusinessPlan.setEnabled(false);
        BusinessPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusinessPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel20)
                                    .addComponent(numberE)
                                    .addComponent(cityOrABN)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel25))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(planIDfield)
                                    .addComponent(employeesField)
                                    .addComponent(cityOrABNField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(monthField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dayField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(capLimitField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(internetQuotaField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(memorySizeField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usernameField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(PersonalPlan)
                                .addGap(18, 18, 18)
                                .addComponent(BusinessPlan))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(updateButton)
                        .addGap(106, 106, 106)
                        .addComponent(clearButtun)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BusinessPlan)
                            .addComponent(PersonalPlan))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(modelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(memorySizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(internetQuotaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(capLimitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(dayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityOrABN)
                    .addComponent(cityOrABNField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberE)
                    .addComponent(employeesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(clearButtun))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void planIDfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planIDfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planIDfieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            String username = usernameField.getText();
            String model = modelField.getText();
            MobileType type = MobileType.valueOf(typeBox.getSelectedItem().toString());
            int size = Integer.parseInt(memorySizeField.getText());
            double price = Double.parseDouble(priceField.getText());
            int quota = Integer.parseInt(internetQuotaField.getText());
            int cap = Integer.parseInt(capLimitField.getText());
            int day = Integer.parseInt(dayField.getText());
            int month = Integer.parseInt(monthField.getText());
            int year = Integer.parseInt(yearField.getText());
            MyDate date = new MyDate(year, month, day);
            MobilePhone phone = new MobilePhone(model, type, size, price);
            plan.setUserName(username);
            plan.setMobilePhone(phone);
            plan.setInternetQuota(quota);
            plan.setCapLimit(cap);
            plan.setExpiryDate(date);
            if (PersonalPlan.isSelected()) {
                String city = cityOrABN.getText();
                ((PersonalPlan) plan).setCity(city);
            } else {
                int abn = Integer.parseInt(cityOrABNField.getText());
                int noEmp = Integer.parseInt(employeesField.getText());
                ((BusinessPlan) plan).setABN(abn);
                ((BusinessPlan) plan).setNumE(noEmp);
            }
            JOptionPane.showMessageDialog(this, " plan has been updated.");
            userUI.fillTable();
            userUI.filterTable();
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtunActionPerformed
        employeesField.setText("");
        cityOrABNField.setText("");
        yearField.setText("");
        monthField.setText("");
        dayField.setText("");
        capLimitField.setText("");
        internetQuotaField.setText("");
        priceField.setText("");
        memorySizeField.setText("");
        modelField.setText("");
        usernameField.setText("");

    }//GEN-LAST:event_clearButtunActionPerformed

    private void PersonalPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalPlanActionPerformed
        // TODO add your handling code here:
        employeesField.setVisible(false);
        numberE.setVisible(false);
        cityOrABN.setText("City");
    }//GEN-LAST:event_PersonalPlanActionPerformed

    private void BusinessPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusinessPlanActionPerformed
        // TODO add your handling code here:

        cityOrABN.setText("ABN");
        numberE.setVisible(true);
        employeesField.setVisible(true);
    }//GEN-LAST:event_BusinessPlanActionPerformed

    private void cityOrABNFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityOrABNFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityOrABNFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BusinessPlan;
    private javax.swing.JRadioButton PersonalPlan;
    private javax.swing.JTextField capLimitField;
    private javax.swing.JLabel cityOrABN;
    private javax.swing.JTextField cityOrABNField;
    private javax.swing.JButton clearButtun;
    private javax.swing.JTextField dayField;
    private javax.swing.JTextField employeesField;
    private javax.swing.JTextField internetQuotaField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField memorySizeField;
    private javax.swing.JTextField modelField;
    private javax.swing.JTextField monthField;
    private javax.swing.JLabel numberE;
    private javax.swing.JTextField planIDfield;
    private javax.swing.JTextField priceField;
    private javax.swing.JComboBox<String> typeBox;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}
